name: Coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    name: Generate coverage report
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run tests with coverage
        run: |
          ./gradlew :api:test :api:jacocoTestReport --continue
          ./gradlew :core:test :core:jacocoTestReport --continue
          ./gradlew :importer:test :importer:jacocoTestReport --continue
          ./gradlew :loaders:file-loader:test :loaders:file-loader:jacocoTestReport --continue
          ./gradlew :loaders:mysql-loader:test :loaders:mysql-loader:jacocoTestReport --continue
          ./gradlew :loaders:mongo-loader:test :loaders:mongo-loader:jacocoTestReport --continue
          ./gradlew :loaders:redis-loader:test :loaders:redis-loader:jacocoTestReport --continue
          ./gradlew :plugin:test :plugin:jacocoTestReport --continue

      - name: Upload to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          codecov_yml_path: codecov.yml
          directory: .
          disable_search: true
          fail_ci_if_error: true
          files: >-
            api/build/reports/jacoco/test/jacocoTestReport.xml,
            core/build/reports/jacoco/test/jacocoTestReport.xml,
            importer/build/reports/jacoco/test/jacocoTestReport.xml,
            loaders/file-loader/build/reports/jacoco/test/jacocoTestReport.xml,
            loaders/mysql-loader/build/reports/jacoco/test/jacocoTestReport.xml,
            loaders/mongo-loader/build/reports/jacoco/test/jacocoTestReport.xml,
            loaders/redis-loader/build/reports/jacoco/test/jacocoTestReport.xml,
            plugin/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: github-actions
          override_branch: ${{ github.ref_name }}
          override_build: ${{ github.run_id }}
          override_build_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          override_commit: ${{ github.sha }}
          slug: pirawis/AdvancedSlimePaper
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
